### ISSUE TITLE
"An unexpected error occured trying to execute that command"

### ISSUE THREAD

**Issue by RuafuMan-Obs** [GeheimagentNr1/MoreMobGriefingOptions#3]
**Versions**
Minecraft Version: [1.20.1]
Minecraft Forge Version: [47.1.33]
Mod Version: [e.g. 2.0.3]

**Log files**
Please append the log, debug-log and if available the crash-log files.
[latest.log](https://github.com/GeheimagentNr1/MoreMobGriefingOptions/files/12093398/latest.log)

**Describe the bug**
"An unexpected error occured trying to execute that command"
I tried multi entities ,all the same

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
Disable creepers' mobgriefing

**Screenshots**
![2023-07-19_17 27 21](https://github.com/GeheimagentNr1/MoreMobGriefingOptions/assets/33950546/30e3dc92-94ac-416b-bd6f-03045eae914f)

**Additional context**

┆Issue is synchronized with this [Trello card](https://trello.com/c/rNeCxlyT) by [Unito](https://www.unito.io)

**Comment by GeheimagentNr1** [comment]
Are you playing in a single player world or on a server?  
In a single player world, are cheats enabled?  
On a server are you OP with permission level 4?

**Comment by RuafuMan-Obs** [comment]
Single player,cheats enabled
mod list:
![image](https://github.com/GeheimagentNr1/MoreMobGriefingOptions/assets/33950546/aa233541-b56b-4aa9-8d98-7ab8080fed1e)

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td>Investigations running</td></tr><tr><th>Issue type:</th><td>Bug</td></tr><tr><th>Fix type:</th><td>Bugfix</td></tr><tr><th>Fix version:</th><td>tba</td></tr><tr><th>Fix release date:</th><td>tba</td></tr></tbody></table>

**Issue confirmed for:**

*   Minecraft version: 1.20.1  
    Forge version: 47.1.42  
    Mod version: 2.0.3

**TODOs:**

*   [x] Test with Minecraft version 1.20.1, Forge version 47.1.42, Mod version 2.0.3

**Comment by GeheimagentNr1** [comment]
I could reproduce the issue, I will fix it as soon as possible.

As a workaround, you can go to the folder "saves" > "Name of your world/save game" > "serverconfig". There you can find a file named "moremobgriefingoptions.toml". In this file, you can set the mobgriefing option per entity (The command is doing the same).

**Comment by GeheimagentNr1** [comment]
Issue is fixed with version 2.0.4  
Have fun playing and thank you for reporting.
