### ISSUE TITLE
since it doesnt let me comment on curseforge i will write the issue with the mod here in hopes of a fix.

### ISSUE THREAD

**Issue by Jeffrichards1** [GeheimagentNr1/MoreMobGriefingOptions#4]
The issue is with the 1.20.1 version of the mod.I cant dissable the TnT damage to blocks with the command "/mobgriefing minecraft:tnt false" it doesnt work at all.I have tried with other entyties such as the creeper and its explosion damage was removed. So please fix this issue or suggest me how to do the command properly.

Thanks in advance!

**Comment by GeheimagentNr1** [comment]
MoreMobgriefingOptions only adds: That the mobriefing decided by the mobGriefing gamerule, can be configured per entity Because TNT is not influenced by the mobGriefing gamerule, changing the mobgriefing configuration of TNT have an effect.
